/* This software is licensed under XorGame 1.0 license. License does not expire.
 * Can be used for creating unlimited applications.
 * Can be distributed in binary or object form only.
 * Non-commercial use only.
 * Cannot modify source-code for any purpose (cannot create derivative works).
 */
package xorgame.client;

import java.awt.*;
import static xorgame.client.Shared.*;

/**
 * Panel with buttons used to switch between game areas. 
 * @author Artur
 */
public class ControlPanel extends javax.swing.JPanel {
    
    Main main;
    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {
        initComponents();
    }
    
    /**
     * Sets reference to main window of the client. Used to get session data and controler. 
     * @param main_ Referense to main window of the client. 
     */
    public void setMainParent(Main main_) {
        main = main_;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonsPanel = new javax.swing.JPanel();
        previewButton = new javax.swing.JButton();
        buildingsButton = new javax.swing.JButton();
        researchButton = new javax.swing.JButton();
        shipyardButton = new javax.swing.JButton();
        defenseButton = new javax.swing.JButton();
        fleetButton = new javax.swing.JButton();
        galaxyButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        messagesButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        ButtonsPanel.setBackground(new java.awt.Color(0, 0, 25));
        ButtonsPanel.setLayout(new java.awt.GridLayout(9, 0, 5, 5));

        previewButton.setBackground(new java.awt.Color(0, 0, 25));
        previewButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Preview.png", BUTTON_SIZE));
        previewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        previewButton.setContentAreaFilled(false);
        previewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                previewButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                previewButtonMouseExited(evt);
            }
        });
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(previewButton);

        buildingsButton.setBackground(new java.awt.Color(0, 0, 25));
        buildingsButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Buildings.png", BUTTON_SIZE));
        buildingsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        buildingsButton.setContentAreaFilled(false);
        buildingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buildingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buildingsButtonMouseExited(evt);
            }
        });
        buildingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingsButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(buildingsButton);

        researchButton.setBackground(new java.awt.Color(0, 0, 25));
        researchButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Research.png", BUTTON_SIZE));
        researchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        researchButton.setContentAreaFilled(false);
        researchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                researchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                researchButtonMouseExited(evt);
            }
        });
        researchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                researchButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(researchButton);

        shipyardButton.setBackground(new java.awt.Color(0, 0, 25));
        shipyardButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Shipyard.png", BUTTON_SIZE));
        shipyardButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        shipyardButton.setContentAreaFilled(false);
        shipyardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shipyardButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shipyardButtonMouseExited(evt);
            }
        });
        shipyardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shipyardButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(shipyardButton);

        defenseButton.setBackground(new java.awt.Color(0, 0, 25));
        defenseButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Defense.png", BUTTON_SIZE));
        defenseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        defenseButton.setContentAreaFilled(false);
        defenseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                defenseButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                defenseButtonMouseExited(evt);
            }
        });
        defenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defenseButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(defenseButton);

        fleetButton.setBackground(new java.awt.Color(0, 0, 25));
        fleetButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Fleet.png", BUTTON_SIZE));
        fleetButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        fleetButton.setContentAreaFilled(false);
        fleetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fleetButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fleetButtonMouseExited(evt);
            }
        });
        fleetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fleetButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(fleetButton);

        galaxyButton.setBackground(new java.awt.Color(0, 0, 25));
        galaxyButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Galaxy.png", BUTTON_SIZE));
        galaxyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        galaxyButton.setContentAreaFilled(false);
        galaxyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                galaxyButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                galaxyButtonMouseExited(evt);
            }
        });
        galaxyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galaxyButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(galaxyButton);

        settingsButton.setBackground(new java.awt.Color(0, 0, 25));
        settingsButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Settings.png", BUTTON_SIZE));
        settingsButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        settingsButton.setContentAreaFilled(false);
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(settingsButton);

        messagesButton.setBackground(new java.awt.Color(0, 0, 25));
        messagesButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Messages.png", BUTTON_SIZE));
        messagesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        messagesButton.setContentAreaFilled(false);
        messagesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                messagesButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                messagesButtonMouseExited(evt);
            }
        });
        messagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messagesButtonActionPerformed(evt);
            }
        });
        ButtonsPanel.add(messagesButton);

        add(ButtonsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void previewButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewButtonMouseEntered
        previewButton.setIcon(loadIcon("/xorgame/client/GUI_EN/PreviewActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_previewButtonMouseEntered

    private void previewButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previewButtonMouseExited
        previewButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Preview.png", BUTTON_SIZE));
    }//GEN-LAST:event_previewButtonMouseExited

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        //main.getMaterials().updateComboBox();
        main.getMaterials().updateMaterials();
        main.getPreview().updatePreview();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "PreviewCard");
        playSound("/Resources/button.wav");
    }//GEN-LAST:event_previewButtonActionPerformed

    private void buildingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingsButtonMouseEntered
        buildingsButton.setIcon(loadIcon("/xorgame/client/GUI_EN/BuildingsActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_buildingsButtonMouseEntered

    private void buildingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buildingsButtonMouseExited
        buildingsButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Buildings.png", BUTTON_SIZE));
    }//GEN-LAST:event_buildingsButtonMouseExited

    private void buildingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingsButtonActionPerformed
        main.getMaterials().updateMaterials();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "BuildingsCard");
        playSound("/Resources/button.wav");
        main.getBuildings().updateBuildings();
    }//GEN-LAST:event_buildingsButtonActionPerformed

    private void researchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchButtonMouseEntered
        researchButton.setIcon(loadIcon("/xorgame/client/GUI_EN/ResearchActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_researchButtonMouseEntered

    private void researchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_researchButtonMouseExited
        researchButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Research.png", BUTTON_SIZE));
    }//GEN-LAST:event_researchButtonMouseExited

    private void researchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_researchButtonActionPerformed
        main.getMaterials().updateMaterials();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "ResearchCard");
        playSound("/Resources/button.wav");
        main.getResearch().updateResearch();
    }//GEN-LAST:event_researchButtonActionPerformed

    private void shipyardButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipyardButtonMouseEntered
        shipyardButton.setIcon(loadIcon("/xorgame/client/GUI_EN/ShipyardActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_shipyardButtonMouseEntered

    private void shipyardButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shipyardButtonMouseExited
        shipyardButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Shipyard.png", BUTTON_SIZE));
    }//GEN-LAST:event_shipyardButtonMouseExited

    private void shipyardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shipyardButtonActionPerformed
        main.getMaterials().updateMaterials();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "ShipyardCard");
        playSound("/Resources/button.wav");
        main.getShipyard().updateShipyard();
    }//GEN-LAST:event_shipyardButtonActionPerformed

    private void defenseButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defenseButtonMouseEntered
        defenseButton.setIcon(loadIcon("/xorgame/client/GUI_EN/DefenseActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_defenseButtonMouseEntered

    private void defenseButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_defenseButtonMouseExited
        defenseButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Defense.png", BUTTON_SIZE));
    }//GEN-LAST:event_defenseButtonMouseExited

    private void defenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defenseButtonActionPerformed
        main.getMaterials().updateMaterials();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "DefenseCard");
        playSound("/Resources/button.wav");
        main.getDefense().updateDefense();
    }//GEN-LAST:event_defenseButtonActionPerformed

    private void fleetButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fleetButtonMouseEntered
        fleetButton.setIcon(loadIcon("/xorgame/client/GUI_EN/FleetActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_fleetButtonMouseEntered

    private void fleetButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fleetButtonMouseExited
        fleetButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Fleet.png", BUTTON_SIZE));
    }//GEN-LAST:event_fleetButtonMouseExited

    private void fleetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fleetButtonActionPerformed
        main.getMaterials().updateMaterials();
        main.getFleet().setStartCoordinates();
        main.getFleet().setContent();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "FleetCard");
        playSound("/Resources/button.wav");
    }//GEN-LAST:event_fleetButtonActionPerformed

    private void galaxyButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_galaxyButtonMouseEntered
        galaxyButton.setIcon(loadIcon("/xorgame/client/GUI_EN/GalaxyActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_galaxyButtonMouseEntered

    private void galaxyButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_galaxyButtonMouseExited
        galaxyButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Galaxy.png", BUTTON_SIZE));
    }//GEN-LAST:event_galaxyButtonMouseExited

    private void galaxyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galaxyButtonActionPerformed
        main.getMaterials().updateMaterials();
        main.getGalaxy().updatePlanets();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "GalaxyCard");
        playSound("/Resources/button.wav");
    }//GEN-LAST:event_galaxyButtonActionPerformed

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        settingsButton.setIcon(loadIcon("/xorgame/client/GUI_EN/SettingsActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
        settingsButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Settings.png", BUTTON_SIZE));
    }//GEN-LAST:event_settingsButtonMouseExited

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        main.getMaterials().updateMaterials();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "SettingsCard");
        playSound("/Resources/button.wav");
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void messagesButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagesButtonMouseEntered
        messagesButton.setIcon(loadIcon("/xorgame/client/GUI_EN/MessagesActive.png", BUTTON_SIZE));
    }//GEN-LAST:event_messagesButtonMouseEntered

    private void messagesButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagesButtonMouseExited
        messagesButton.setIcon(loadIcon("/xorgame/client/GUI_EN/Messages.png", BUTTON_SIZE));
    }//GEN-LAST:event_messagesButtonMouseExited

    private void messagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messagesButtonActionPerformed
        main.getMaterials().updateMaterials();
        main.getMessages().updateMessages();
        CardLayout layout = (CardLayout)main.getWorkPanel().getLayout();
        layout.show(main.getWorkPanel(), "MessagesCard");
        playSound("/Resources/button.wav");
    }//GEN-LAST:event_messagesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton buildingsButton;
    private javax.swing.JButton defenseButton;
    private javax.swing.JButton fleetButton;
    private javax.swing.JButton galaxyButton;
    private javax.swing.JButton messagesButton;
    private javax.swing.JButton previewButton;
    private javax.swing.JButton researchButton;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton shipyardButton;
    // End of variables declaration//GEN-END:variables
}
