/* This software is licensed under XorGame 1.0 license. License does not expire.
 * Can be used for creating unlimited applications.
 * Can be distributed in binary or object form only.
 * Non-commercial use only.
 * Cannot modify source-code for any purpose (cannot create derivative works).
 */
package xorgame.client;

import xorgame.*;
import static xorgame.client.Shared.*;

/**
 * Panel containing descriptions of all defense systems. 
 * @author Artur
 */
public class Defense extends javax.swing.JPanel {
    
    Main main;

    /**
     * Creates new form Defense
     */
    public Defense() {
        initComponents();
    }
    
    /**
     * Sets reference to main window of the client. Used to get session data and controler. 
     * @param main_ Referense to main window of the client. 
     */
    public void setMainParent(Main main_) {
        main = main_;
        
        rocketLauncher.setMainParent(main); 
        laserCannon.setMainParent(main);
        turbolaser.setMainParent(main);
        ionCannon.setMainParent(main);
        tractorBeam.setMainParent(main);
        plasmaCannon.setMainParent(main);
        heavyPlasmaCannon.setMainParent(main);
    }
    
    /**
     * Sets icons and names of all defense systems. 
     */
    public void setContent() {
        rocketLauncher.setContent(ShipyardItem.RocketLauncher, "/Resources/General_GUI/RocketLauncher.jpg"); 
        laserCannon.setContent(ShipyardItem.LaserGun, "/Resources/General_GUI/LaserGun.jpg"); 
        turbolaser.setContent(ShipyardItem.TurboLaserGun, "/Resources/General_GUI/TurboLaserGun.jpg"); 
        ionCannon.setContent(ShipyardItem.IonGun, "/Resources/General_GUI/IonGun.jpg"); 
        tractorBeam.setContent(ShipyardItem.TractorGun, "/Resources/General_GUI/TractorGun.jpg"); 
        plasmaCannon.setContent(ShipyardItem.PlasmaGun, "/Resources/General_GUI/PlasmaGun.jpg"); 
        heavyPlasmaCannon.setContent(ShipyardItem.HeavyPlasmaGun, "/Resources/General_GUI/HeavyPlasmaGun.jpg");
    }
    
    /**
     * Updates description of all defense systems - cost and building time. 
     */
    public void updateDefense() {
        rocketLauncher.updateDescription();
        laserCannon.updateDescription();
        turbolaser.updateDescription();
        ionCannon.updateDescription();
        tractorBeam.updateDescription();
        plasmaCannon.updateDescription();
        heavyPlasmaCannon.updateDescription();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        defenseCardPanel = new javax.swing.JPanel();
        defenseScrollPanel = new javax.swing.JScrollPane();
        defensePanel = new javax.swing.JPanel();
        rocketLauncher = new xorgame.client.DefenseDescription();
        laserCannon = new xorgame.client.DefenseDescription();
        turbolaser = new xorgame.client.DefenseDescription();
        ionCannon = new xorgame.client.DefenseDescription();
        tractorBeam = new xorgame.client.DefenseDescription();
        plasmaCannon = new xorgame.client.DefenseDescription();
        heavyPlasmaCannon = new xorgame.client.DefenseDescription();

        setLayout(new java.awt.BorderLayout());

        defenseCardPanel.setBackground(new java.awt.Color(0, 0, 25));
        defenseCardPanel.setLayout(new java.awt.BorderLayout());

        defenseScrollPanel.getVerticalScrollBar().setUnitIncrement(SCROLL_SPEED);

        defensePanel.setBackground(new java.awt.Color(0, 0, 25));
        defensePanel.setLayout(new java.awt.GridLayout(7, 1, 10, 10));
        defensePanel.add(rocketLauncher);
        defensePanel.add(laserCannon);
        defensePanel.add(turbolaser);
        defensePanel.add(ionCannon);
        defensePanel.add(tractorBeam);
        defensePanel.add(plasmaCannon);
        defensePanel.add(heavyPlasmaCannon);

        defenseScrollPanel.setViewportView(defensePanel);

        defenseCardPanel.add(defenseScrollPanel, java.awt.BorderLayout.CENTER);

        add(defenseCardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel defenseCardPanel;
    private javax.swing.JPanel defensePanel;
    private javax.swing.JScrollPane defenseScrollPanel;
    private xorgame.client.DefenseDescription heavyPlasmaCannon;
    private xorgame.client.DefenseDescription ionCannon;
    private xorgame.client.DefenseDescription laserCannon;
    private xorgame.client.DefenseDescription plasmaCannon;
    private xorgame.client.DefenseDescription rocketLauncher;
    private xorgame.client.DefenseDescription tractorBeam;
    private xorgame.client.DefenseDescription turbolaser;
    // End of variables declaration//GEN-END:variables
}
