/* This software is licensed under XorGame 1.0 license. License does not expire.
 * Can be used for creating unlimited applications.
 * Can be distributed in binary or object form only.
 * Non-commercial use only.
 * Cannot modify source-code for any purpose (cannot create derivative works).
 */
package xorgame.client;

import java.io.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.SQLException;
import xorgame.*;
import java.awt.*;
import java.awt.image.*;
import javax.imageio.ImageIO;

/**
 * Panel with general data - planet image, name and user statistics. 
 * @author Artur
 */
public class Preview extends javax.swing.JPanel {

    Main main;
    /**
     * Creates new form Preview
     */
    public Preview() {
        initComponents();
    }
    
    /**
     * Sets reference to main window of the client. Used to get session data and controler.
     * @param main_ Main window of the client. 
     */
    public void setMainParent(Main main_) {
        main = main_;
    }
    
    /**
     * Updates user nick, user statistics and currently built orders. 
     */
    public void updatePreview() {
        titlePreviewButton.setText(main.getSelectedPlanet().getName());
        
        planetImagePreviewLabelComponentResized(null);
        
        usernamePreviewLabel.setText(main.getUser().getNick()); 
        totalPointsPreviewLabel.setText(Integer.toString(main.getMainControler().getTotalPoints(main.getUser().getNick())));
        economyPointsPreviewLabel.setText(Integer.toString(main.getMainControler().getEconomyPoints(main.getUser().getNick())));
        researchPointsPreviewLabel.setText(Integer.toString(main.getMainControler().getResearchPoints(main.getUser().getNick())));
        militaryPointsPreviewLabel.setText(Integer.toString(main.getMainControler().getMilitaryPoints(main.getUser().getNick())));
        
        buildingOrdersList.removeAll();
        researchOrdersList.removeAll();
        shipyardOrdersList.removeAll();
        flightsList.removeAll();
        
        DefaultListModel buildings = new DefaultListModel();
        for(BuildingOrder ord : main.getSelectedPlanet().getBuildingOrderSet()) 
            buildings.addElement(ord.toString());
        buildingOrdersList.setModel(buildings);
        
        DefaultListModel research = new DefaultListModel();
        for(ResearchOrder ord : main.getSelectedPlanet().getResearchOrderSet()) 
            research.addElement(ord.toString());
        researchOrdersList.setModel(research);
        
        DefaultListModel shipyard = new DefaultListModel();
        for(ShipyardOrder ord : main.getSelectedPlanet().getShipyardOrderSet()) 
            shipyard.addElement(ord.toString());
        shipyardOrdersList.setModel(shipyard);
        
        DefaultListModel flights = new DefaultListModel();
        for(Flight ord : main.getSelectedPlanet().getFlightSet()) 
            flights.addElement(ord.toString());
        
        for(Flight ord : main.getSelectedPlanet().getFlightSet1())
            flights.addElement(ord.toString());
        flightsList.setModel(flights);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        previewCardPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        titlePreviewButton = new javax.swing.JButton();
        abandonButton = new javax.swing.JButton();
        planetImagePreviewLabel = new javax.swing.JLabel();
        statsPreviewPanel = new javax.swing.JPanel();
        userPreviewLabel = new javax.swing.JLabel();
        usernamePreviewLabel = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        totalPointsPreviewLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        economyPointsPreviewLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        researchPointsPreviewLabel = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        militaryPointsPreviewLabel = new javax.swing.JLabel();
        ordersPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        buildingOrdersList = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        researchScrolss = new javax.swing.JScrollPane();
        researchOrdersList = new javax.swing.JList<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        shipyardOrdersList = new javax.swing.JList<>();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        flightsList = new javax.swing.JList<>();

        setBackground(new java.awt.Color(0, 255, 51));
        setLayout(new java.awt.BorderLayout());

        previewCardPanel.setBackground(new java.awt.Color(0, 0, 25));
        previewCardPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(0, 0, 25));
        headerPanel.setLayout(new java.awt.GridBagLayout());

        titlePreviewButton.setBackground(new java.awt.Color(0, 0, 25));
        titlePreviewButton.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        titlePreviewButton.setForeground(new java.awt.Color(255, 255, 255));
        titlePreviewButton.setText("...");
        titlePreviewButton.setToolTipText("Click to change planet name");
        titlePreviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlePreviewButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.4;
        headerPanel.add(titlePreviewButton, gridBagConstraints);

        abandonButton.setBackground(new java.awt.Color(153, 0, 0));
        abandonButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        abandonButton.setForeground(new java.awt.Color(255, 255, 255));
        abandonButton.setText("Abandon");
        abandonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abandonButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        headerPanel.add(abandonButton, gridBagConstraints);

        previewCardPanel.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        planetImagePreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        planetImagePreviewLabel.setText("jLabel22");
        planetImagePreviewLabel.setMinimumSize(new java.awt.Dimension(300, 300));
        planetImagePreviewLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                planetImagePreviewLabelComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                planetImagePreviewLabelComponentShown(evt);
            }
        });
        previewCardPanel.add(planetImagePreviewLabel, java.awt.BorderLayout.CENTER);

        statsPreviewPanel.setBackground(new java.awt.Color(0, 0, 25));
        statsPreviewPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        statsPreviewPanel.setLayout(new java.awt.GridLayout(5, 3));

        userPreviewLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userPreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        userPreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userPreviewLabel.setText("User:");
        statsPreviewPanel.add(userPreviewLabel);

        usernamePreviewLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernamePreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernamePreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernamePreviewLabel.setText("jLabel21");
        statsPreviewPanel.add(usernamePreviewLabel);
        statsPreviewPanel.add(jLabel27);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Total points:");
        statsPreviewPanel.add(jLabel33);

        totalPointsPreviewLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalPointsPreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalPointsPreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPointsPreviewLabel.setText("jLabel21");
        statsPreviewPanel.add(totalPointsPreviewLabel);
        statsPreviewPanel.add(jLabel25);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Economy points:");
        statsPreviewPanel.add(jLabel35);

        economyPointsPreviewLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        economyPointsPreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        economyPointsPreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        economyPointsPreviewLabel.setText("jLabel21");
        statsPreviewPanel.add(economyPointsPreviewLabel);
        statsPreviewPanel.add(jLabel26);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Research points:");
        statsPreviewPanel.add(jLabel36);

        researchPointsPreviewLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        researchPointsPreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        researchPointsPreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        researchPointsPreviewLabel.setText("jLabel21");
        statsPreviewPanel.add(researchPointsPreviewLabel);
        statsPreviewPanel.add(jLabel28);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Military points:");
        statsPreviewPanel.add(jLabel38);

        militaryPointsPreviewLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        militaryPointsPreviewLabel.setForeground(new java.awt.Color(255, 255, 255));
        militaryPointsPreviewLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        militaryPointsPreviewLabel.setText("jLabel21");
        statsPreviewPanel.add(militaryPointsPreviewLabel);

        previewCardPanel.add(statsPreviewPanel, java.awt.BorderLayout.PAGE_END);

        ordersPanel.setBackground(new java.awt.Color(0, 0, 25));
        ordersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        ordersPanel.setLayout(new java.awt.GridBagLayout());

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Building orders:");
        jLabel21.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jLabel21, gridBagConstraints);

        buildingOrdersList.setBackground(new java.awt.Color(0, 0, 25));
        buildingOrdersList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buildingOrdersList.setForeground(new java.awt.Color(255, 255, 255));
        buildingOrdersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        buildingOrdersList.setVisibleRowCount(4);
        jScrollPane2.setViewportView(buildingOrdersList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jScrollPane2, gridBagConstraints);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Research orders:");
        jLabel22.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jLabel22, gridBagConstraints);

        researchOrdersList.setBackground(new java.awt.Color(0, 0, 25));
        researchOrdersList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        researchOrdersList.setForeground(new java.awt.Color(255, 255, 255));
        researchOrdersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        researchOrdersList.setVisibleRowCount(4);
        researchScrolss.setViewportView(researchOrdersList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(researchScrolss, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Shipyard orders:");
        jLabel23.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jLabel23, gridBagConstraints);

        shipyardOrdersList.setBackground(new java.awt.Color(0, 0, 25));
        shipyardOrdersList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        shipyardOrdersList.setForeground(new java.awt.Color(255, 255, 255));
        shipyardOrdersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        shipyardOrdersList.setVisibleRowCount(4);
        jScrollPane3.setViewportView(shipyardOrdersList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jScrollPane3, gridBagConstraints);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Fleets:");
        jLabel24.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jLabel24, gridBagConstraints);

        flightsList.setBackground(new java.awt.Color(0, 0, 25));
        flightsList.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        flightsList.setForeground(new java.awt.Color(255, 255, 255));
        flightsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        flightsList.setVisibleRowCount(4);
        jScrollPane4.setViewportView(flightsList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.weighty = 0.25;
        ordersPanel.add(jScrollPane4, gridBagConstraints);

        previewCardPanel.add(ordersPanel, java.awt.BorderLayout.LINE_END);

        add(previewCardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void planetImagePreviewLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_planetImagePreviewLabelComponentResized
        try {
            byte[] plImg = null;

            if(main.getSelectedPlanet() != null) {
                for(PlanetGui img: main.getGui().getPlanetGui()) {
                    if(img.getId() == main.getSelectedPlanet().getGui()) {
                        plImg = img.getImage();
                        break;
                    }
                }

                Image scaled;
                BufferedImage planetImage = ImageIO.read(new ByteArrayInputStream(plImg));
                if(planetImagePreviewLabel.getWidth() < planetImagePreviewLabel.getHeight()) {
                    scaled = planetImage.getScaledInstance(
                        planetImagePreviewLabel.getWidth(),
                        planetImage.getHeight() * planetImagePreviewLabel.getWidth() / planetImage.getWidth(),
                        Image.SCALE_DEFAULT );
                }
                else {
                    scaled = planetImage.getScaledInstance(
                        planetImage.getWidth() * planetImagePreviewLabel.getHeight() / planetImage.getHeight(),
                        planetImagePreviewLabel.getHeight(),
                        Image.SCALE_FAST );
                }

                planetImagePreviewLabel.setIcon(new ImageIcon(scaled));
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_planetImagePreviewLabelComponentResized

    private void planetImagePreviewLabelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_planetImagePreviewLabelComponentShown

    }//GEN-LAST:event_planetImagePreviewLabelComponentShown

    private void titlePreviewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlePreviewButtonActionPerformed
        String newName = JOptionPane.showInputDialog(this, "Enter new name of planet" + main.getSelectedPlanet().getName());
        if(!newName.isEmpty()) {
            try {
                main.getMainControler().changePlanetName(main.getSelectedPlanet().getPlanetPK(), newName);
                titlePreviewButton.setText(newName);
                main.getMaterials().updateMaterials();
                main.getMaterials().updateComboBox();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error while changing planet name!", "Error", JOptionPane.ERROR_MESSAGE);
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_titlePreviewButtonActionPerformed

    private void abandonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abandonButtonActionPerformed
        if(JOptionPane.showConfirmDialog(main, "Do you really want to abandon this planet?", "Really?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try { 
                main.getMainControler().abandonPlanet(main.getSelectedPlanet().getPlanetPK());
                main.getPreview().updatePreview();
                JOptionPane.showMessageDialog(main, "Planet successfully abandoned!"); 
                main.getMaterials().updateComboBox();
            } catch (SQLException ex) {
                Logger.getLogger(Preview.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_abandonButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abandonButton;
    private javax.swing.JList<String> buildingOrdersList;
    private javax.swing.JLabel economyPointsPreviewLabel;
    private javax.swing.JList<String> flightsList;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel militaryPointsPreviewLabel;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JLabel planetImagePreviewLabel;
    private javax.swing.JPanel previewCardPanel;
    private javax.swing.JList<String> researchOrdersList;
    private javax.swing.JLabel researchPointsPreviewLabel;
    private javax.swing.JScrollPane researchScrolss;
    private javax.swing.JList<String> shipyardOrdersList;
    private javax.swing.JPanel statsPreviewPanel;
    private javax.swing.JButton titlePreviewButton;
    private javax.swing.JLabel totalPointsPreviewLabel;
    private javax.swing.JLabel userPreviewLabel;
    private javax.swing.JLabel usernamePreviewLabel;
    // End of variables declaration//GEN-END:variables
}
