/* This software is licensed under XorGame 1.0 license. License does not expire.
 * Can be used for creating unlimited applications.
 * Can be distributed in binary or object form only.
 * Non-commercial use only.
 * Cannot modify source-code for any purpose (cannot create derivative works).
 */
package xorgame.client;

import xorgame.*;
import static xorgame.client.Shared.*;

/**
 * Panel containing descriptions of all technologies in the game. 
 * @author Artur
 */
public class ResearchPanel extends javax.swing.JPanel {

    Main main;
    
    /**
     * Creates new form Research
     */
    public ResearchPanel() {
        initComponents();
    }
    
    /**
     * Sets reference to main window of the client. Used to get session data and controler.
     * @param main_ Referense to main window of the client. 
     */
    public void setMainParent(Main main_) {
        main = main_;
        energetic.setMainParent(main); 
        nanotechnology.setMainParent(main); 
        astrophysics.setMainParent(main); 
        hyperspace.setMainParent(main); 
        astronavigation.setMainParent(main); 
        laser.setMainParent(main); 
        ion.setMainParent(main); 
        plasma.setMainParent(main); 
        gravitons.setMainParent(main); 
        combat.setMainParent(main); 
        shield.setMainParent(main); 
        material.setMainParent(main); 
        ionEngine.setMainParent(main); 
        hyperEngine.setMainParent(main); 
    }
    
    /**
     * Sets technologies names and icons. 
     */
    public void setContent() {
        energetic.setContent(Research.Energetic, "/Resources/General_GUI/Energetic.jpg");
        nanotechnology.setContent(Research.Nanotechnology, "/Resources/General_GUI/Nanotechnology.jpg");
        astrophysics.setContent(Research.Astrophysics, "/Resources/General_GUI/Astrophysics.jpg");
        hyperspace.setContent(Research.Hyperspace, "/Resources/General_GUI/Hyperspace.jpg");
        astronavigation.setContent(Research.Astronavigation, "/Resources/General_GUI/Astronavigation.jpg");
        laser.setContent(Research.Laser, "/Resources/General_GUI/Laser.jpg");
        ion.setContent(Research.Ion, "/Resources/General_GUI/Ion.jpg");
        plasma.setContent(Research.Plasma, "/Resources/General_GUI/Plasma.jpg");
        gravitons.setContent(Research.Gravitons, "/Resources/General_GUI/Gravitons.jpg");
        combat.setContent(Research.Combat, "/Resources/General_GUI/Combat.jpg");
        shield.setContent(Research.Shield, "/Resources/General_GUI/Shield.jpg");
        material.setContent(Research.Material, "/Resources/General_GUI/Material.jpg");
        ionEngine.setContent(Research.IonEngine, "/Resources/General_GUI/IonEngine.jpg");
        hyperEngine.setContent(Research.HyperEngine, "/Resources/General_GUI/HyperEngine.jpg");
    }
    
    /**
     * Updates descriptions of all technologies - cost and research time. 
     */
    public void updateResearch() {
        energetic.updateDescription();
        nanotechnology.updateDescription();
        astrophysics.updateDescription();
        hyperspace.updateDescription();
        astronavigation.updateDescription();
        laser.updateDescription();
        ion.updateDescription();
        plasma.updateDescription();
        gravitons.updateDescription();
        combat.updateDescription();
        shield.updateDescription();
        material.updateDescription();
        ionEngine.updateDescription();
        hyperEngine.updateDescription();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        researchCardPanel = new javax.swing.JPanel();
        researchScrollPanel = new javax.swing.JScrollPane();
        researchPanel = new javax.swing.JPanel();
        energetic = new xorgame.client.ResearchDescription();
        nanotechnology = new xorgame.client.ResearchDescription();
        astrophysics = new xorgame.client.ResearchDescription();
        hyperspace = new xorgame.client.ResearchDescription();
        astronavigation = new xorgame.client.ResearchDescription();
        laser = new xorgame.client.ResearchDescription();
        ion = new xorgame.client.ResearchDescription();
        plasma = new xorgame.client.ResearchDescription();
        gravitons = new xorgame.client.ResearchDescription();
        combat = new xorgame.client.ResearchDescription();
        shield = new xorgame.client.ResearchDescription();
        material = new xorgame.client.ResearchDescription();
        ionEngine = new xorgame.client.ResearchDescription();
        hyperEngine = new xorgame.client.ResearchDescription();

        setLayout(new java.awt.BorderLayout());

        researchCardPanel.setBackground(new java.awt.Color(0, 0, 25));
        researchCardPanel.setLayout(new java.awt.BorderLayout());

        researchScrollPanel.getVerticalScrollBar().setUnitIncrement(SCROLL_SPEED);

        researchPanel.setBackground(new java.awt.Color(0, 0, 25));
        researchPanel.setLayout(new java.awt.GridLayout(14, 1, 10, 10));
        researchPanel.add(energetic);
        researchPanel.add(nanotechnology);
        researchPanel.add(astrophysics);
        researchPanel.add(hyperspace);
        researchPanel.add(astronavigation);
        researchPanel.add(laser);
        researchPanel.add(ion);
        researchPanel.add(plasma);
        researchPanel.add(gravitons);
        researchPanel.add(combat);
        researchPanel.add(shield);
        researchPanel.add(material);
        researchPanel.add(ionEngine);
        researchPanel.add(hyperEngine);

        researchScrollPanel.setViewportView(researchPanel);

        researchCardPanel.add(researchScrollPanel, java.awt.BorderLayout.CENTER);

        add(researchCardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private xorgame.client.ResearchDescription astronavigation;
    private xorgame.client.ResearchDescription astrophysics;
    private xorgame.client.ResearchDescription combat;
    private xorgame.client.ResearchDescription energetic;
    private xorgame.client.ResearchDescription gravitons;
    private xorgame.client.ResearchDescription hyperEngine;
    private xorgame.client.ResearchDescription hyperspace;
    private xorgame.client.ResearchDescription ion;
    private xorgame.client.ResearchDescription ionEngine;
    private xorgame.client.ResearchDescription laser;
    private xorgame.client.ResearchDescription material;
    private xorgame.client.ResearchDescription nanotechnology;
    private xorgame.client.ResearchDescription plasma;
    private javax.swing.JPanel researchCardPanel;
    private javax.swing.JPanel researchPanel;
    private javax.swing.JScrollPane researchScrollPanel;
    private xorgame.client.ResearchDescription shield;
    // End of variables declaration//GEN-END:variables
}
