/* This software is licensed under XorGame 1.0 license. License does not expire.
 * Can be used for creating unlimited applications.
 * Can be distributed in binary or object form only.
 * Non-commercial use only.
 * Cannot modify source-code for any purpose (cannot create derivative works).
 */
package xorgame.client;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static xorgame.client.Shared.*;

/**
 * Panel with account settings - allows to change user nick, password or to delete account. 
 * @author Artur
 */
public class Settings extends javax.swing.JPanel {
    Main main;

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
    }
    
    /**
     * Sets reference to main window of the client. Used to get session data and controler.
     * @param main_ Referense to main window of the client. 
     */
    public void setMainParent(Main main_) {
        main = main_;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        changeNickTextField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        changePasswordTextField = new javax.swing.JPasswordField();
        jLabel24 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        confirmPasswordTextField = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        deleteAccountCheckBox = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 25));
        setLayout(new java.awt.GridLayout(2, 1));

        jPanel15.setBackground(new java.awt.Color(0, 0, 25));
        jPanel15.setLayout(new java.awt.GridBagLayout());

        jPanel16.setBackground(new java.awt.Color(0, 0, 25));
        jPanel16.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel16.setLayout(new java.awt.GridLayout(1, 3, 50, 50));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Change nick:");
        jPanel16.add(jLabel21);
        jPanel16.add(changeNickTextField);
        jPanel16.add(jLabel22);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel15.add(jPanel16, gridBagConstraints);

        jPanel17.setBackground(new java.awt.Color(0, 0, 25));
        jPanel17.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        jPanel17.setLayout(new java.awt.GridLayout(2, 1));

        jPanel18.setBackground(new java.awt.Color(0, 0, 25));
        jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel18.setLayout(new java.awt.GridLayout(1, 3, 50, 50));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Change password:");
        jPanel18.add(jLabel23);
        jPanel18.add(changePasswordTextField);
        jPanel18.add(jLabel24);

        jPanel17.add(jPanel18);

        jPanel19.setBackground(new java.awt.Color(0, 0, 25));
        jPanel19.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel19.setLayout(new java.awt.GridLayout(1, 3, 50, 50));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Confirm new password:");
        jPanel19.add(jLabel25);
        jPanel19.add(confirmPasswordTextField);
        jPanel19.add(jLabel26);

        jPanel17.add(jPanel19);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.2;
        jPanel15.add(jPanel17, gridBagConstraints);

        jPanel20.setBackground(new java.awt.Color(0, 0, 25));
        jPanel20.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel20.setLayout(new java.awt.GridLayout(1, 3, 50, 50));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Delete account");
        jPanel20.add(jLabel27);

        deleteAccountCheckBox.setBackground(new java.awt.Color(0, 0, 25));
        jPanel20.add(deleteAccountCheckBox);
        jPanel20.add(jLabel28);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel15.add(jPanel20, gridBagConstraints);

        jPanel21.setBackground(new java.awt.Color(0, 0, 25));
        jPanel21.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        jPanel21.setLayout(new java.awt.GridLayout(1, 3, 50, 50));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jPanel21.add(jLabel29);

        saveButton.setBackground(new java.awt.Color(0, 102, 51));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("SAVE CHANGES");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel21.add(saveButton);
        jPanel21.add(jLabel30);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel15.add(jPanel21, gridBagConstraints);

        add(jPanel15);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            boolean succedeed = false;
            //change nick
            if(!changeNickTextField.getText().isEmpty()) {
                if(isAlphanumeric(changeNickTextField.getText())) {
                    main.getMainControler().setUserNick(main.getUser().getNick(), changeNickTextField.getText());
                    main.updateUserSessionData(changeNickTextField.getText());
                    JOptionPane.showMessageDialog(main, "Nick changed!");
                    succedeed = true;
                }
                else {
                    JOptionPane.showMessageDialog(main, "Nick may contain only letters and digits!", "Error", JOptionPane.ERROR_MESSAGE); 
                }
            }
            //change password
            if(!changePasswordTextField.getText().isEmpty()) {
                if(changePasswordTextField.getText().equals(confirmPasswordTextField.getText())) {
                    main.getMainControler().setUserPassword(main.getUser().getNick(), changePasswordTextField.getText());
                    main.updateUserSessionData(main.getUser().getNick());
                    JOptionPane.showMessageDialog(main, "Password changed!"); 
                    succedeed = true;
                }
                else {
                    JOptionPane.showMessageDialog(main, "Passwords must be the same!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            //delete account
            if(deleteAccountCheckBox.isSelected()) {
                if(JOptionPane.showConfirmDialog(main, "Do you really want to delete your account? It is irreversible!", "Really?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    main.getMainControler().deleteUser(main.getUser().getNick()); 
                    succedeed = true;
                }
            }
            
            if(succedeed) {
                JOptionPane.showMessageDialog(main, "You will be relogged now!", "Success!", JOptionPane.ERROR_MESSAGE); 
                CardLayout layout = (CardLayout)main.getContentPane().getLayout();
                layout.show(main.getContentPane(), "LoginRegister");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField changeNickTextField;
    private javax.swing.JPasswordField changePasswordTextField;
    private javax.swing.JPasswordField confirmPasswordTextField;
    private javax.swing.JCheckBox deleteAccountCheckBox;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
