/* This software is licensed under XorGame 1.0 license. License does not expire.
 * Can be used for creating unlimited applications.
 * Can be distributed in binary or object form only.
 * Non-commercial use only.
 * Cannot modify source-code for any purpose (cannot create derivative works).
 */
package xorgame.client;

import xorgame.*;
import static xorgame.client.Shared.*;

/**
 * Panel with descriptions of all ships in the game. 
 * @author Artur
 */
public class Shipyard extends javax.swing.JPanel {

    Main main;
    
    /**
     * Creates new form Shipyard
     */
    public Shipyard() {
        initComponents();
    }
    
    /**
     * Sets reference to main window of the client. Used to get session data and controler.
     * @param main_ Referense to main window of the client. 
     */
    public void setMainParent(Main main_) {
        main = main_;
        
        solarSat.setMainParent(main); 
        transporter.setMainParent(main); 
        freighter.setMainParent(main); 
        recycler.setMainParent(main); 
        colonizer.setMainParent(main); 
        spySond.setMainParent(main); 
        fighter.setMainParent(main); 
        ionFighter.setMainParent(main); 
        frigate.setMainParent(main); 
        bomber.setMainParent(main); 
        cruiser.setMainParent(main); 
        drednot.setMainParent(main); 
        destroyer.setMainParent(main); 
        deathStar.setMainParent(main); 
    }
    
    /**
     * Sets names and icons of all ships. 
     */
    public void setContent() {
        solarSat.setContent(ShipyardItem.SolarSat, "/Resources/General_GUI/SolarSat.jpg");
        transporter.setContent(ShipyardItem.Transporter, "/Resources/General_GUI/Transporter.jpg");
        freighter.setContent(ShipyardItem.Freighter, "/Resources/General_GUI/Freighter.jpg");
        recycler.setContent(ShipyardItem.Recycler, "/Resources/General_GUI/Recycler.jpg");
        colonizer.setContent(ShipyardItem.Colonizer, "/Resources/General_GUI/Colonizer.jpg");
        spySond.setContent(ShipyardItem.SpySond, "/Resources/General_GUI/SpySond.jpg");
        fighter.setContent(ShipyardItem.Fighter, "/Resources/General_GUI/Fighter.jpg");
        ionFighter.setContent(ShipyardItem.IonFighter, "/Resources/General_GUI/IonFighter.jpg");
        frigate.setContent(ShipyardItem.Frigate, "/Resources/General_GUI/Frigate.jpg");
        bomber.setContent(ShipyardItem.Bomber, "/Resources/General_GUI/Bomber.jpg");
        cruiser.setContent(ShipyardItem.Cruiser, "/Resources/General_GUI/Cruiser.jpg");
        drednot.setContent(ShipyardItem.Drednot, "/Resources/General_GUI/Drednot.jpg");
        destroyer.setContent(ShipyardItem.Destroyer, "/Resources/General_GUI/Destroyer.jpg");
        deathStar.setContent(ShipyardItem.DeathStar, "/Resources/General_GUI/DeathStar.jpg");
    }
    
    /**
     * Updates descriptions of all ships. Downloads data from the game server. 
     */
    public void updateShipyard() {
        solarSat.updateDescription();
        transporter.updateDescription();
        freighter.updateDescription();
        recycler.updateDescription();
        colonizer.updateDescription();
        spySond.updateDescription();
        fighter.updateDescription();
        ionFighter.updateDescription();
        frigate.updateDescription();
        bomber.updateDescription();
        cruiser.updateDescription();
        drednot.updateDescription();
        destroyer.updateDescription();
        deathStar.updateDescription();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shipyardCardPanel = new javax.swing.JPanel();
        shipyardScrollPanel = new javax.swing.JScrollPane();
        shipyardPanel = new javax.swing.JPanel();
        solarSat = new xorgame.client.ShipyardDescription();
        transporter = new xorgame.client.ShipyardDescription();
        freighter = new xorgame.client.ShipyardDescription();
        recycler = new xorgame.client.ShipyardDescription();
        colonizer = new xorgame.client.ShipyardDescription();
        spySond = new xorgame.client.ShipyardDescription();
        fighter = new xorgame.client.ShipyardDescription();
        ionFighter = new xorgame.client.ShipyardDescription();
        frigate = new xorgame.client.ShipyardDescription();
        bomber = new xorgame.client.ShipyardDescription();
        cruiser = new xorgame.client.ShipyardDescription();
        drednot = new xorgame.client.ShipyardDescription();
        destroyer = new xorgame.client.ShipyardDescription();
        deathStar = new xorgame.client.ShipyardDescription();

        setLayout(new java.awt.BorderLayout());

        shipyardCardPanel.setBackground(new java.awt.Color(0, 0, 25));
        shipyardCardPanel.setLayout(new java.awt.BorderLayout());

        shipyardScrollPanel.getVerticalScrollBar().setUnitIncrement(SCROLL_SPEED);

        shipyardPanel.setBackground(new java.awt.Color(0, 0, 25));
        shipyardPanel.setLayout(new java.awt.GridLayout(14, 1, 10, 10));
        shipyardPanel.add(solarSat);
        shipyardPanel.add(transporter);
        shipyardPanel.add(freighter);
        shipyardPanel.add(recycler);
        shipyardPanel.add(colonizer);
        shipyardPanel.add(spySond);
        shipyardPanel.add(fighter);
        shipyardPanel.add(ionFighter);
        shipyardPanel.add(frigate);
        shipyardPanel.add(bomber);
        shipyardPanel.add(cruiser);
        shipyardPanel.add(drednot);
        shipyardPanel.add(destroyer);
        shipyardPanel.add(deathStar);

        shipyardScrollPanel.setViewportView(shipyardPanel);

        shipyardCardPanel.add(shipyardScrollPanel, java.awt.BorderLayout.CENTER);

        add(shipyardCardPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private xorgame.client.ShipyardDescription bomber;
    private xorgame.client.ShipyardDescription colonizer;
    private xorgame.client.ShipyardDescription cruiser;
    private xorgame.client.ShipyardDescription deathStar;
    private xorgame.client.ShipyardDescription destroyer;
    private xorgame.client.ShipyardDescription drednot;
    private xorgame.client.ShipyardDescription fighter;
    private xorgame.client.ShipyardDescription freighter;
    private xorgame.client.ShipyardDescription frigate;
    private xorgame.client.ShipyardDescription ionFighter;
    private xorgame.client.ShipyardDescription recycler;
    private javax.swing.JPanel shipyardCardPanel;
    private javax.swing.JPanel shipyardPanel;
    private javax.swing.JScrollPane shipyardScrollPanel;
    private xorgame.client.ShipyardDescription solarSat;
    private xorgame.client.ShipyardDescription spySond;
    private xorgame.client.ShipyardDescription transporter;
    // End of variables declaration//GEN-END:variables
}
